-- Drop all tables
DROP TABLE IF EXISTS "Notification" CASCADE;
DROP TABLE IF EXISTS "Enrollment" CASCADE;
DROP TABLE IF EXISTS "GradeSection" CASCADE;
DROP TABLE IF EXISTS "Student" CASCADE;
DROP TABLE IF EXISTS "AcademicYear" CASCADE;
DROP TABLE IF EXISTS "Admin" CASCADE;
DROP TABLE IF EXISTS "_prisma_migrations" CASCADE;

-- Drop all enums
DROP TYPE IF EXISTS "Section" CASCADE;
DROP TYPE IF EXISTS "Gender" CASCADE;
DROP TYPE IF EXISTS "EnrollmentStatus" CASCADE;
DROP TYPE IF EXISTS "NotificationType" CASCADE;
